### ISSUE TITLE
It seems that loss of fcdd is different from paper?

### ISSUE THREAD

**Issue by captainfffsama** [liznerski/fcdd#16]
![fcdd_loss](https://user-images.githubusercontent.com/40843698/124567744-dbcbb600-de76-11eb-8129-996eb8511251.png)
In paper,**"the center corresponds to the bias term in the last layer of our networks"**,but in code [1](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/training/fcdd.py#L19) [2](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/models/fcdd_cnn_224.py#L114) seems we juse think `c=0`?

**Comment by liznerski** [comment]
As you can see [here](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/models/bases.py#L240), the conv layers have bias per default. Thus, the [final conv layer](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/models/fcdd_cnn_224.py#L114) of FCDD_CNN224_VGG also has bias. This holds for all networks. Besides, per default, bias is activated in all intermediate layers as well (see [here](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/runners/argparse_configs.py#L160)) since if one uses some sort of anomalies (may them be artificial or not), weight collapse to zero is no longer an issue.

**Comment by captainfffsama** [comment]
> As you can see [here](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/models/bases.py#L240), the conv layers have bias per default. Thus, the [final conv layer](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/models/fcdd_cnn_224.py#L114) of FCDD_CNN224_VGG also has bias. This holds for all networks. Besides, per default, bias is activated in all intermediate layers as well (see [here](https://github.com/liznerski/fcdd/blob/7f1119c635ea242ca6416dd14d153f4a31771b4c/python/fcdd/runners/argparse_configs.py#L160)) since if one uses some sort of anomalies (may them be artificial or not), weight collapse to zero is no longer an issue.

thanks for you answer and excellent work. As you say that weight collapse to zero  is easy,so when we set `c` as any make sense value like `c=1`, this objective function still work?

**Comment by captainfffsama** [comment]
OK, I just try set `c=1` ,and run a train on my custom dataset, It seems that result is close to `c=0`... So  maybe we set `c` as any make sense value, the network is still work
