### ISSUE TITLE
Can we use ResNet for FCDD?

### ISSUE THREAD

**Issue by cinout** [liznerski/fcdd#35]
Hi. Thank you for sharing your excellent work with us.

I am replacing VGG with **Resnet-18** for MVTec training. When the model runs, this error would occur:

`  File "fcdd/python/fcdd/models/bases.py", line 88, in receptive_upsample
    res = torch.nn.functional.conv_transpose2d(
RuntimeError: negative output_padding is not supported`

The output_padding calculated by the `receptive_upsample` is a negative value.

I have inherited the FCDDNet, and used `_create_conv2d` and `_create_maxpool2d` as replacement for `torch.nn.Conv2d` and `torch.nn.MaxPool2d`.

I wonder if ResNet can be considered as a valid type of FCDD? Much appreciation for your help!

**Comment by liznerski** [comment]
Hey. 

Have a look at #11. In general, a ResNet is valid for FCDD, but for deeper versions I'd suspect the heatmaps to become imprecise due to the large receptive field. Although the residual connections might aid a bit. 
An issue of your implementation might be that the receptive field surpasses the image size. I think that that might cause the problem.

Cheers

**Comment by cinout** [comment]
Hi,

Thank you for the quick reply.

The issue turns out to be in the residual connection step (downsampling) of Resnet, where an `nn.Conv2d()` layer is applied. For this layer, please do not replace it with `_create_conv2d`, as it does not affect the receptive field of the model.

Hope this helps for anyone who wants to combine ResNet with FCDD.

Cheers.
