### ISSUE TITLE
Issue with running on custom dataset with --supervise_mode == unsupervised

### ISSUE THREAD

**Issue by Davidyao99** [liznerski/fcdd#41]
Hi, thank you so much for the well organized and documented codebase. 

I am trying to run your code on a custom dataset and setting the supervise_mode to unsupervised. However, the code seems to get stuck on Generating dataset preview.... Any idea why? When I run the same code with supervise_mode parameter set to malformed_normal, it works fine. 

Thank you!

Edit: I found the reason. In datasets\bases.py file, the preview function keeps loading in training data until we have a certain amount of abnormal and normal images. For unsupervised setting, there will not be abnormal images, hence the loop keeps going. I changed that portion of the code and it works now. ;)

**Comment by liznerski** [comment]
Hey. 
You're right. Though the preview works in the unsupervised case, it doesn't return early and iterates through the full data loader once. Probably no one ever noticed since typically the datasets for AD are rather small. Still, I pushed a small update that fixes this ([6cd3947](https://github.com/liznerski/fcdd/commit/6cd39476f3232166e5ebdfbce55e3e806f082186)). 
Thanks!
