### ISSUE TITLE
ModuleNotFoundError: No module named 'fcdd'

### ISSUE THREAD

**Issue by EudicL** [liznerski/fcdd#43]
Hi, How to solve this problem please?

Traceback (most recent call last):
  File "runners/run_mvtec.py", line 1, in <module>
    from fcdd.runners.bases import ClassesRunner
ModuleNotFoundError: No module named 'fcdd'

**Comment by liznerski** [comment]
Hey. Did you install FCDD properly ([see here](https://github.com/liznerski/fcdd#installation)), and if you used a virtual environment, did you activate it before executing the scripts?

**Comment by Stephenhua** [comment]
Hey, the image of the model input is RGB or BGR. I am not clear it, thanks.

**Comment by liznerski** [comment]
Hey. It's RGB since we use Pillow to load and process the images. However, some functionalities for displaying and storing images like the heatmaps use OpenCV instead, for which the images are temporarily transformed into BGR. You will see that in the code.

**Comment by Stephenhua** [comment]
> Hey. It's RGB since we use Pillow to load and process the images. However, some functionalities for displaying and storing images like the heatmaps use OpenCV instead, for which the images are temporarily transformed into BGR. You will see that in the code.

Thank you for your  reply, I understand this problem. Now , I meet a new problem,  If I want to get  anomaly socre of the picture, I need to choose  ||A(X)||_1 or  ascore.reshape(ascore.size(0),-1).mean(1).  The |||A(X)|_1 means pixiels anomaly score, the other is mean value of  ||A(X)||_1.  So , What is the difference between them？

**Comment by liznerski** [comment]
The pixel-wise score is actually just A(X). If you got confused by [this line](https://github.com/liznerski/fcdd/blob/master/python/fcdd/training/bases.py#L147), note that it computes the mean over the channels and since there is just one channel, it essentially does nothing. The sample-wise anomaly score is the mean over the spatial dimensions (height and width), so just one scalar per sample that determines how overall anomalous the sample is. This is what you use for detection.
