### ISSUE TITLE
How to start an inference test after completed training

### ISSUE THREAD

**Issue by Rodn3y** [liznerski/fcdd#44]
How do i start an inference after i have completed the training?

I started training with mvtec ad dataset class 7 with:
$ python runners/run_single_mvtec.py --normal-class 7

Training works perfect but how can i make an inference from my own image of a screw after training is done?

What size should the inference image file be? Does it need to be resized before inference?

**Comment by liznerski** [comment]
Hey. 

There's a script for that purpose ([here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_prediction_with_snapshot.py)). It takes a snapshot of the trained model to produce anomaly scores and heatmaps for any images. Since you trained on MVTec, you just have to change a few lines: [47](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_prediction_with_snapshot.py#L47) to point to your snapshot, [54](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_prediction_with_snapshot.py#L54) to point to your own images, [57](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_prediction_with_snapshot.py#L57) to set the trained class, and [72](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_prediction_with_snapshot.py#L72) to set a target directory for the heatmaps. 

If you need any help, let me know.

**Comment by Rodn3y** [comment]
Thank you very much for you reply! 

I Changed the lines accordingly and run_prediction_with_snapshot.py

I placed 2 Images (224*224) in foo/myimages/image_x.png

Line 72 and 73 looking like this now:

**72 logger = None 
73 Logger("results/foo")**

If i run the .py the console output is: 

python run_prediction_with_snapshot.py 
/home/jan/Documents/venv/lib/python3.8/site-packages/torchvision/models/_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and will be removed in 0.15. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
Loaded net_state, opt_state, sched_state with starting epoch 200 for fcdd.training.fcdd.FCDDTrainer
tensor([0.9013, 0.4015])

which looks fine i guess. But unfortunately there are no heatmaps generated in "results/foo directory. 

are line 72 and 73 fine? If I comment out line 72 (73 staying) I just get "NameError: name 'logger' is not defined"

**Comment by Rodn3y** [comment]
works perfect! Ty

**Comment by francesco28597** [comment]
Hi,
I'm trying to make inference after having trained a 224_VGG model on a custom dataset (using the _run_custom.py_ runner) and I can't understand how to configure the variable _transform_ in this script.

What are the default _transform_ steps performed on custom datasets?

**Comment by liznerski** [comment]
Hey. You can find the default transformations for custom datasets [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/image_folder.py#L100). This is because the default argument for the preprocessing pipeline (i.e., transformations) is set to `aug1` as you can see [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/argparse_configs.py#L88). The custom dataset automatically computes the empirical mean and std of the normal training data. To get the same mean and std for interference, you can just put a print [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/image_folder.py#L92).
