### ISSUE TITLE
pip install fcdd

### ISSUE THREAD

**Issue by ShawnGao123** [liznerski/fcdd#48]
I want to install fcdd on Windows 10, when I use pip install fcdd, there is an error:

(venv) D:\python38\venv\Scripts>pip install fcdd
ERROR: Could not find a version that satisfies the requirement fcdd (from versions: none)
ERROR: No matching distribution found for fcdd

How can I solve this problem? Thanks.

**Comment by liznerski** [comment]
FCDD is not registered in PyPI. You'll need to download the code from this repository and follow the instructions ([here](https://github.com/liznerski/fcdd#installation)) to install it. That is, you'll need to traverse to the `python` directory of the code (https://github.com/liznerski/fcdd/tree/master/python) and execute `pip install .` instead of `pip install fcdd`. Maybe that's your error?

**Comment by ShawnGao123** [comment]
Thanks! I got it.
I have another question. When I finished the training, which file folder saves the final trained model (.pt or .ptb)?

**Comment by liznerski** [comment]
Have a look [here](https://github.com/liznerski/fcdd#explanation-of-the-log-data) for an explanation of the log data. The saved model for normal class *x* for the first iteration (random seed) can be found at `/log_directory/normal_x/it_1 `.
