### ISSUE TITLE
FCDD model without bias raises AssertionError: VGG net is only supported with bias atm!

### ISSUE THREAD

**Issue by layadas** [liznerski/fcdd#55]
I am trying to implement the default FCDD model (`FCDD_CNN224_VGG_F`) without any biases, since there are batch norm layers after conv layers throughout the model, but I get an `AssertionError`. It looks like I can edit the code and set `bias=False` in `models/bases.py`, but I am not sure if this will cause any inconsistencies with the results or their interpretation. Could you please clarify if simply changing the value of `bias` in the model descriptions in the code will work, or if it is more involved than that? Thank you in advance for any help.

**Comment by liznerski** [comment]
Hey. You need to change the code so that it removes the bias of all layers. This is not implemented right now, which is why the assertion throws an error. Bias can be removed by setting ``bias=False`` to all calls of self._create_conv2d [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/models/fcdd_cnn_224.py#L73). You also have to remove the bias weights from the state dictionary of the pre-trained model [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/models/fcdd_cnn_224.py#L105). Otherwise, the code will throw an error that the state dictionaries do not match.

**Comment by layadas** [comment]
Ok. As long as the results are interpretable as earlier, I can try to make the changes. Thank you for the suggestion.
