### ISSUE TITLE
Training on grayscale images

### ISSUE THREAD

**Issue by NimaDL** [liznerski/fcdd#66]
The code only accept RGB input data for the training and when I tried to feed grayscale images to the model it failed. Any idea how to modify the code to accept grayscale images

**Comment by liznerski** [comment]
Hi!

For custom data? 

Quick and dirty solution: Just repeat the channels for all images. For example, you could add `transforms.Grayscale(num_output_channels=3), ` to the data pre-processing pipeline [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/image_folder.py#L102) and [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/image_folder.py#L108).

The clean solution is defining a network architecture that works with grayscale images. Instead of 3 channels, the first layer needs to expect one channel. For our non-pretrained [VGG](https://github.com/liznerski/fcdd/blob/master/python/fcdd/models/fcdd_cnn_224.py#L17) variant, you need to change the first layer to `self._create_conv2d(1, 64, 3, 1, 1),`. Note that per default the custom data trainer uses the pretrained variant.

**Comment by NimaDL** [comment]
Thank you for your answer.
