### ISSUE TITLE
noise_mode for custom data

### ISSUE THREAD

**Issue by NimaDL** [liznerski/fcdd#67]
Hi

I was wondering which noise mode should I choose to better fit the model on my custom data (the data is from completely different domain than ImageNet). I want to train the model using semi-supervise approach where I show only few anomalous data to the model during the training phase. I am a bit confused what noise model should be chosen? In this case isn't better not to use noise mode option? I am not sure if this option is possible in this version of FCDD!?

**Comment by liznerski** [comment]
Use `--supervise-mode other`. In that case, `--noise-mode` is ignored since the training will use ground-truth anomalies. Follow the description provided [here](https://github.com/liznerski/fcdd/blob/master/python/fcdd/datasets/image_folder.py#L30) on where to place the ground-truth anomalies for training.
